language: c++

sudo: false

jobs:
  include:
    - stage: compile osx
      os: osx
      osx_image: xcode10.1
      before_install:
        - brew install gcc@6
      env:
        - CMAKE_OPTIONS="-DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6"
      #deploy:
        #provider: releases
        #api_key: $GITHUB_TOKEN
        #draft: true
        #skip_cleanup: true
        #file: build/sdg-${TRAVIS_OS_NAME}.tar.gz
        #on:
        #  tags: true
    - stage: compile linux
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        #- MATRIX_EVAL="CC=gcc-6 && CXX=g++-6 && GCOV=gcov-6 && DEPLOY=true"
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - CMAKE_OPTIONS="-DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6"
      #deploy:
      #  - provider: releases
      #    api_key: $GITHUB_TOKEN
      #    draft: false
      #    skip_cleanup: true
      #    file: build/sdg-${TRAVIS_OS_NAME}.tar.gz
      #    on:
      #      tags: true
      #  - provider: pages
      #    skip_cleanup: true
      #    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
      #    local_dir: build/doc/sphinx
      #    on:
      #      branch: master
      #      condition: $DEPLOY = true

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - .travis/build.sh

